language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qY
  - sudo apt-get upgrade -qY
  - sudo apt-get install gcc-multilib -qY

script:
  - ./make.sh

git:
  submodules: false
