language: c

compiler:
  - gcc
  - clang

script:
  - ./make.sh

git:
  submodules: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "nvn/kowNi9+ji+I3gYBUAv3xy1KFZQztXXtYjfdblwxgUK5vmEze/RcuHzamLQXtHHxsoDMma4F+9iqyMY3HgPGtXJYY8KHU1HVUdJA6mK0Cexbb+yJ5MIKfPPdqta4CUqBsKBcOZDnihymYRSnmLe1jk+jgxPa0efc6xF+UJow="

notifications:
  email: false

addons:
  coverity_scan:
    project:
      name: "ETrun/ETrun"
      description: "Build submitted via Travis CI"
    build_command: "./make.sh"
    branch_pattern: master