language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -q
  - sudo apt-get upgrade -q
  - sudo apt-get install gcc-multilib -q

script:
  - ./make.sh

git:
  submodules: false
