language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install gcc-multilib -q

script:
  - ./make.sh

git:
  submodules: false

notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.org#etrun"
    use_notice: false
    skip_join: true
